---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: builder
    image: rockylinux/rockylinux:9-ubi
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
